name: AUR

on: workflow_dispatch

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Import SSH key
        id: key
        run: |
          echo "Importing SSH ley..."
          echo "${{ secrets.ID_RSA }}" | base64 -d > ~./.ssh/id_rsa
          echo "Updating ~/.ssh/known_hosts..."
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          echo "Step completed"

      - name: Checkout AUR repo
        id: checkout
        run: git clone ssh://aur@aur.archlinux.org/figma-linux.git ./

      - name: Update PKGBUILD
        id: pkgbuild
        run: |
          sed -i "s/$prevVersion/$version/" ./PKGBUILD
