name: Build

on:
  create:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build in Docker
        run: |
          docker build -t figma-linux-artefacts -f "./Build_artefacts_local" .
          mkdir -p ./build/installers
          docker cp $(docker create figma-linux-artefacts:latest)://usr/src/figma-linux/build/installers/. ./build/installers

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/installers/figma-linux*
          tag: ${{ github.ref }}
          body: "Release description"
          overwrite: true
          file_glob: true
