name: Build

on:
  create:
    tags:
    - 'v*.*.*'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache src
        id: cache-src
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: ./*

  build_arm64v8:
    needs: setup
    name: build for arm64v8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: repo
        path: ./

    - name: Setup
      run: |
        chmod +wr . -R
        chmod +x ./**/*.sh
        chmod +x ./**/*.pl

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build in Docker
      id: build
      run: |
        docker buildx build --platform linux/arm64 -t 4tqrgqe5yrgfd/figma-linux-artefacts-arm --load -f ./docker/Build_artefacts_arm64v8 .
        mkdir -p ./build/installers
        docker cp $(docker create 4tqrgqe5yrgfd/figma-linux-artefacts-arm)://usr/src/figma-linux/build/installers/. ./build/installers
        perl ./scripts/generate_release_notes.pl

    - name: Cache arm64v8 artifacts
      id: cache-arm64v8-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arm64v8
        path: build/installers/*

  release_arm64v8:
    name: Upload arm64v8 assets
    runs-on: ubuntu-latest
    needs: build_arm64v8
    steps:
      - name: mkdir installers
        run: mkdir -p ./build/installers

      - uses: actions/download-artifact@v2
        with:
          name: arm64v8
          path: ./build/installers

      - name: Get version
        id: version
        run: |
          ls -la .
          ls -la ./build
          ls -la ./build/installers
          echo ::set-output name=release::$(cat build/installers/version)
          sha256sum ./build/installers/figma-linux* || echo ""

      - name: Upload release assets
        id: release
        uses: ChugunovRoman/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Figma Linux ${{ steps.version.outputs.release }}
          files: build/installers/figma-linux*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_amd64:
    runs-on: ubuntu-latest
    name: build for amd64
    needs: setup
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: repo
          path: ./

      - name: Setup
        run: |
          chmod +wr . -R
          chmod +x ./**/*.sh
          chmod +x ./**/*.pl

      - name: Build in Docker
        id: build
        run: |
          docker build -t figma-linux-artefacts -f "./docker/Build_artefacts_local" .
          mkdir -p ./build/installers
          docker cp $(docker create figma-linux-artefacts:latest)://usr/src/figma-linux/build/installers/. ./build/installers
          mv ./build/installers/figma-linux_$(cat build/installers/version)_linux_x64.zip ./build/installers/figma-linux_$(cat build/installers/version)_linux_amd64.zip
          perl ./scripts/generate_release_notes.pl

      - name: Cache amd64 artifacts
        id: cache-amd64-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: amd64
          path: |
            ./release_notes
            build/installers/*

  release_amd64:
    name: Upload amd64 assets
    runs-on: ubuntu-latest
    needs: build_amd64
    steps:
      - name: mkdir installers
        run: mkdir -p ./build/installers

      - uses: actions/download-artifact@v2
        with:
          name: amd64
          path: ./

      - name: Get version
        id: version
        run: |
          ls -la .
          ls -la ./build
          ls -la ./build/installers
          echo ::set-output name=release::$(cat build/installers/version)
          sha256sum ./build/installers/figma-linux* || echo ""

      - name: Upload release assets
        id: release
        uses: ChugunovRoman/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./release_notes
          name: Figma Linux ${{ steps.version.outputs.release }}
          files: build/installers/figma-linux*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Uncommnet before next release
  # upload_ppa_amd64:
  #   name: Upload to Launchpad PPA
  #   runs-on: ubuntu-latest
  #   needs: build_amd64
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         path: ./

  #     - name: Import keys
  #       run: |
  #         ls -la .
  #         mv ./repo/* ./
  #         mv ./amd64/* ./
  #         rm -rf ./repo
  #         rm -rf ./amd64
  #         ls -la .
  #         chmod +x ./**/*.sh
  #         chmod +x ./**/*.pl
  #         ls -la ./scripts
  #         ls -la ./build
  #         ls -la ./build/installers
  #         mkdir ./gpg
  #         echo "${{ secrets.GPG_PUB_KEY }}" | base64 -d > ./gpg/pub.key
  #         echo "${{ secrets.GPG_SECRET_KEY }}" | base64 -d > ./gpg/secret.key
  #         echo "${{ secrets.GPG_PASSPHRASE_KEY }}" | base64 -d > ./gpg/passphrase
  #         echo "${{ secrets.ID_RSA }}" | base64 -d > ./gpg/id_rsa

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Upload PPA
  #       run: |
  #         ./scripts/build_ppa.sh "1"

  upload_aur:
    name: Upload to AUR
    runs-on: ubuntu-latest
    needs: [release_amd64, release_arm64v8]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Prepare artifacts
        run: |
          ls -la .
          mkdir -p src/build/installers
          mv ./repo/* ./src
          mv ./amd64/build/installers/* ./src/build/installers/
          mv ./arm64v8/* ./src/build/installers/
          rm -rf ./repo
          rm -rf ./amd64
          rm -rf ./arm64v8
          ls -la .
          ls -la ./src
          ls -la ./src/build
          ls -la ./src/build/installers
          find ./ -type f -iname "*.sh" -exec chmod +x {} \;
          find ./ -type f -iname "*.pl" -exec chmod +x {} \;
          rm -rf ./src/build/installers/*.deb
          rm -rf ./src/build/installers/*.pacman
          rm -rf ./src/build/installers/*.rpm
          rm -rf ./src/build/installers/*.AppImage
          rm -rf ./src/build/installers/linux*
          ls -la ./src/build/installers/

      - name: Import SSH key
        id: key
        run: |
          echo "Importing SSH ley..."
          mkdir ~/.ssh
          echo "${{ secrets.ID_RSA }}" | base64 -d > ~/.ssh/id_rsa
          echo "Updating ~/.ssh/known_hosts..."
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "Step completed"

      - name: Checkout AUR repo
        id: checkout
        run: git clone ssh://aur@aur.archlinux.org/figma-linux.git ./aur

      - name: Update PKGBUILD
        id: pkgbuild
        run: |
          prevVersion=$(cat ./aur/PKGBUILD | grep -E 'pkgver=".*"' | tr -d '[a-z="\n]')
          version="$(cat ./src/build/installers/version)"
          ls -la .
          ls -la ./src
          ls -la ./src/build/installers/
          sha256sums_x86_64="$(sha256sum ./src/build/installers/figma-linux_${version}_linux_amd64.zip)"
          sha256sums_aarch64="$(sha256sum ./src/build/installers/figma-linux_${version}_linux_arm64.zip)"
          echo "Bump version from $prevVersion to $version"
          echo "New sha256sums for x86_64: ${sha256sums_x86_64}"
          echo "New sha256sums for aarch64: ${sha256sums_aarch64}"
          sed -i "s/$prevVersion/$version/" ./aur/PKGBUILD
          sed -i "s/$prevVersion/$version/" ./aur/.SRCINFO
          echo "Updating sums..."
          sed -i "s/sha256sums_x86_64 = .*\n/sha256sums_x86_64 = $\{sha256sums_x86_64\}\n/" ./aur/.SRCINFO
          sed -i "s/sha256sums_aarch64 = .*\n/sha256sums_aarch64 = $\{sha256sums_aarch64\}\n/" ./aur/.SRCINFO
          sed -i "s/sha256sums_x86_64=(\".*\")\n/sha256sums_x86_64=(\"$\{sha256sums_x86_64\}\")\n/" ./aur/PKGBUILD
          sed -i "s/sha256sums_aarch64=(\".*\")\n/sha256sums_aarch64=(\"$\{sha256sums_aarch64\}\")\n/" ./aur/PKGBUILD
          echo ::set-output name=release::$version

      - name: Push to AUR
        id: push
        run: |
          git config --global --add user.name "${{ secrets.USER_NAME }}"
          git config --global --add user.email "${{ secrets.EMAIL }}"
          cd ./aur
          git add .
          git commit -m "Release v$version"
          git tag -a v${{ steps.pkgbuild.outputs.release }} -m "Publish v${{ steps.pkgbuild.outputs.release }} version"
          git push --tags origin master

  flatpak:
    name: Update Flatpak
    runs-on: ubuntu-latest
    needs: [release_amd64, release_arm64v8]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Import SSH key
        id: key
        run: |
          echo "Importing SSH ley..."
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" | base64 -d > ~/.ssh/id_rsa
          echo "Updating ~/.ssh/known_hosts..."
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "Step completed"

      - name: Clone repo
        id: clone
        run: git clone git@github.com:flathub/io.github.Figma_Linux.figma_linux.git ./flatpak-repo

      - name: Update configs
        id: update
        run: |
          sudo apt install libxml2-utils -y
          ls -la .
          ls -la ./repo
          ls -la ./repo/scripts
          ls -la ./flatpak-repo
          ls -la ./amd64
          ls -la ./arm64v8
          mv ./amd64/* ./
          mv ./arm64v8/* ./
          rm -rf ./amd64
          rm -rf ./arm64v8
          ls -la .
          find ./ -type f -iname "*.sh" -exec chmod +x {} \;
          find ./ -type f -iname "*.pl" -exec chmod +x {} \;
          cd ./repo
          ./scripts/generate_release_notes.pl 1
          cd ..
          data=$(cat ./repo/release_notes | tr -d '\n')
          cat ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml
          cat ./repo/release_notes
          prevVersion=$(cat ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml | grep -Eo 'release\sversion=".*"\s' | tr -d '[a-z=" \s\n]')
          version="$(cat ./build/installers/version)"
          echo "Bump version from $prevVersion to $version"
          sed -i "s/$prevVersion/$version/" ./flatpak-repo/io.github.Figma_Linux.figma_linux.yml
          sed -i "s/$prevVersion/$version/" ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml
          cat ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml | tr -d '\n' > /tmp/tmp1
          sed -i "s|<description>.\{0,12\}<ul>.*<\/ul>.\{0,12\}<\/description>|<description><ul>$data<\/ul><\/description>|g" /tmp/tmp1
          xmllint --format /tmp/tmp1 > ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml
          cat ./flatpak-repo/io.github.Figma_Linux.figma_linux.appdata.xml
          echo ::set-output name=release::$version

      - name: Push
        id: push
        run: |
          git config --global --add user.name "${{ secrets.USER_NAME }}"
          git config --global --add user.email "${{ secrets.EMAIL }}"
          cd ./flatpak-repo
          git add .
          git commit -m "Release v$version"
          git tag -a v${{ steps.update.outputs.release }} -m "Publish v${{ steps.update.outputs.release }} version"
          git push --tags origin master

