name: Build

on:
  create:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build in Docker
        run: |
          ls -la .
          docker build -t figma-linux-artefacts -f "./Build_artefacts_local" .
          ls -la .
          mkdir -p ./build/installers
          docker cp figma-linux-artefacts:/usr/src/figma-linux/build/installers/. ./build/installers

      # - name: Extract assets
      #   uses: shrink/actions-docker-extract@v1
      #   with:
      #     image: '4tqrgqe5yrgfd/figma-linux-artefacts:latest'
      #     path: /usr/src/figma-linux/build/installers/.

      - name: Check Files
        run: perl -v && ls -la . && ls -la ./build && ls -la ./build/installers
