name: Build

on:
  create:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build in Docker
        run: ./scripts/build_artefacts.sh local && ls -la . && ls -la ./build && ls -la ./build/installers

      - name: Check Files
        run: ls -la . && ls -la ./build && ls -la ./build/installers
