name: Manually Upload to Launchpad PPA

on: workflow_dispatch

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/reuse_setup.yml
    secrets: inherit

  flathub:
    name: Upload
    uses: ./.github/workflows/reuse_launchpad.yml
    secrets: inherit
    needs: setup
