name: Manually Upload to Flathub

on: workflow_dispatch

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/reuse_setup.yml
    secrets: inherit

  flathub:
    name: Upload
    uses: ./.github/workflows/reuse_flatpak.yml
    secrets: inherit
    needs: setup
