name: Release Build

on: workflow_dispatch

jobs:
  setup:
    uses: ./.github/workflows/reuse_setup.yml

  build_arm64v8:
    uses: ./.github/workflows/reuse_build_arm64v8.yml
    needs: setup
  build_amd64:
    uses: ./.github/workflows/reuse_build_amd64.yml
    needs: setup

  release_arm64v8:
    uses: ./.github/workflows/reuse_release_arm64v8.yml
    needs: build_arm64v8
  release_amd64:
    uses: ./.github/workflows/reuse_release_amd64.yml
    needs: build_amd64