name: Artifacts

on:
  schedule:
    - cron: '1 5,17 * * *'

  workflow_dispatch:
    inputs:
      age:
        description: 'Age'
        required: true
        default: '1 hour'

jobs:
  setup:
    name: Remove artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: ${{ github.event.inputs.age }}
