name: amd64

on: workflow_call

jobs:
  release_amd64:
    name: amd64
    runs-on: ubuntu-latest
    steps:
      - name: mkdir installers
        run: mkdir -p ./build/installers

      - uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Get version
        id: version
        run: |
          ls -la .
          echo ::set-output name=release::$(cat build/installers/version)
          sha256sum ./build/installers/figma-linux* || echo ""
          ls -la .

      - name: Upload release assets
        id: release
        uses: ChugunovRoman/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./release_notes
          name: Figma Linux ${{ steps.version.outputs.release }}
          files: build/installers/figma-linux*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}