name: Upload on Launchpad PPA

on: workflow_dispatch

jobs:
  launchpad:
    name: Upload on Launchpad PPA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Import keys
        run: |
          mv ./repo/* ./
          mv ./amd64/* ./
          rm -rf ./repo
          rm -rf ./amd64
          chmod +x ./**/*.sh
          chmod +x ./**/*.pl
          mkdir ./gpg
          echo "${{ secrets.GPG_PUB_KEY }}" | base64 -d > ./gpg/pub.key
          echo "${{ secrets.GPG_SECRET_KEY }}" | base64 -d > ./gpg/secret.key
          echo "${{ secrets.GPG_PASSPHRASE_KEY }}" | base64 -d > ./gpg/passphrase
          echo "${{ secrets.ID_RSA }}" | base64 -d > ./gpg/id_rsa

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Upload PPA
        run: |
          ./scripts/build_ppa.sh "1"